### ISSUE TITLE
WebSocket support..?

### ISSUE THREAD

**Issue by simshanith** [shakyShane/foxy#2]
The TODO checkbox is checked, but I don't see the expected code in index.js from looking at the [nodejitsu/node-http-proxy](https://github.com/nodejitsu/node-http-proxy) docs...

```
//
// Listen to the `upgrade` event and proxy the
// WebSocket requests as well.
//
proxyServer.on('upgrade', function (req, socket, head) {
  proxy.ws(req, socket, head);
});
```

**Comment by buunguyen** [comment]
@shakyShane @simshanith I look at this and https://github.com/BrowserSync/browser-sync/issues/71 (which was closed) but am still not clear on whether I can use BrowserSync with an app that uses socket.io. And there's nothing in the CHANGELOG of this or BrowserSync mentions about it.

Basically I use `node-http-proxy` to proxy API and SocketIO requests from BrowserSync to the backend app but even though I precisely followed the doc of `node-http-proxy`, I couldn't make SocketIO requests work (API requests work though). I'm still trying to make it work, assuming I do some configuration wrong, but it would be nice if you could tell me whether it's possible with BrowserSync at all.  Thanks!

**Comment by simshanith** [comment]
@buunguyen By default, SocketIO requests go to "/socket.io/", so wouldn't get proxied by your custom middleware.

Does your "backend server" also serve your `public` directory? If so, you should probably use BrowserSync's proxy mode.

Current BrowserSync proxy supports Socket.IO over XHR long-polling. With the snippet pasted in my original post opening this issue (#2), it could potentially proxy WebSockets as well.

**Comment by buunguyen** [comment]
@simshanith thank you for your response.

I've configured socket.io to use a custom path `/api/`. In my snippet, you can see I perform the WS upgrade on the server instance started by BrowserSync:
```javascript
 bs.server.on('upgrade', function (req, socket, head) {
   if (/^\/api/i.test(req.url)) {
     httpProxy.ws(req, socket, head)
   }
})
```

The setup is essentially this:

* Express-based API + socket.io (backend) running on port 3001
* Static assets from `public` (frontend) are served by BrowserSync at port 3000
* Backend and frontend are completely separate, one doesn't "contain" another
* JS files (in `public`) make same-domain API and WS requests to port 3000
 * Hence, I want to proxy these requests from port 3000 to 3001 using BrowserSync middleware option and `node-http-proxy`

With the provided snippet, API requests are proxied just fine. So are socket.io long-polling XHR requests, but not WS connections.

Do you think it's possible to make WS work given the above setup?

**Comment by simshanith** [comment]
@buunguyen apologies for the significant delay in response.

After returning to the issue, no, the above setup will not work.

The above setup listens for the `upgrade` on the `proxy` server, not the `foxy` app server. The `foxy` server is where you're attaching the event, but it actually happens on the foxy-internal `proxy` server to which the `foxy` app forwards requests.

I'll see if I can get it working and draft a PR here.

**Comment by simshanith** [comment]
Ok, so a revision of the original synopsis. Looks like the `foxy` server *is* where the event should be attached, but you still weren't using the internal proxy instance.

**Comment by shakyShane** [comment]
Fixed in latest :)

**Comment by buunguyen** [comment]
@simshanith :+1: thanks a lot for working on this.

@shakyShane is this in browser-sync yet? I've just pulled 2.7.0, but still have the same error ("Connection closed before receiving a handshake response"). My usage is:

```js
gulp.task('sync', function (cb) {
  bsync.init({
    ...
    server: {
      middleware: [
        function (req, res, next) {
          if (/^\/api/.test(req.url)) return proxy.web(req, res, {target: 'http://localhost:3000'});
          else next();
        }
      ]
    }
  });
})
```

Do I need to perform WS `upgrade` manually?  I suppose not by looking at the changes, but I'm not very sure.

**Comment by alp82** [comment]
As i am not sure if this is a foxy or BrowserSync problem, i also opened an issue in the other project as well. I apologize if that complicates things.
